# `npm install --location=global pyright`
[[language]]
name = "python"
language-servers = [ "pyright" ]
auto-format = true

# `pip install black`
[language.formatter]
command = "black"
args = [
  "-",
  "--quiet"
]

# `rustup component add rust-analyzer`
[language-server.rust-analyzer.config.check]
command = "clippy"
